trigger:
- main

stages:
- stage: PreBuild
  displayName: 'Pre-Build Steps'
  jobs:
  - job: PreBuild
    displayName: 'Pre-Build'
    pool: myselfagent
    steps:
    - script: |
        cd $(Agent.BuildDirectory)/s
        dir
- stage: DotNetBuild
  displayName: 'Build and Run .NET Core'
  jobs:
  - job: DotNetBuild
    displayName: 'Build and Run'
    pool: myselfagent
   
    steps:
    - task: UseDotNet@2
      inputs:
        packageType: 'sdk'
        version: '9.0.100-preview.3.24204.13'
        installationPath: $(Agent.ToolsDirectory)/dotnet
    - script: dotnet restore
    - script: cd $(Agent.BuildDirectory)/s
    - script: dir
    - script: dotnet build --configuration Release --project $(Agent.BuildDirectory)/s/dotnet/DotNetCoreApp.csproj
    - script: dotnet run --project $(Agent.BuildDirectory)/s/dotnet/DotNetCoreApp.csproj

- stage: NodeBuild
  displayName: 'Build and Run Node.js'
  jobs:
  - job: NodeBuild
    displayName: 'Build and Run'
    pool: myselfagent

    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '16'
    - script: npm install
    - script: npm run build
    - script: node $(Agent.BuildDirectory)/s/node/server.js

- stage: JavaBuild
  displayName: 'Build and Run Java'
  jobs:
  - job: JavaBuild
    displayName: 'Build and Run'
    pool: myselfagent
    steps:
    - task: JavaToolInstaller@0
      inputs:
        versionSpec: '14'
        jdkArchitectureOption: 'x64'
        jdkSourceOption: 'PreInstalled'
    - script: javac -version
    - script: javac -d java/out $(Agent.BuildDirectory)/s/java/HelloWorld.java
    - script: java -cp java/out HelloWorld
